# Generated by Django 4.2.27 on 2025-12-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_candidate_email_candidate_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='confidence_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence score for parsing quality (0.0 to 1.0)', max_digits=3, null=True),
        ),
    ]
