# Generated by Django 4.2.27 on 2025-12-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_candidate_confidence_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='aadhar_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/pan/'),
        ),
    ]
