# Generated by Django 4.2.27 on 2025-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_candidate_aadhar_document_candidate_pan_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='document_request_message',
            field=models.TextField(blank=True, help_text='AI-generated personalized document request email', null=True),
        ),
    ]
